// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJloItz28KY-A2zqdIdPVlD53vrUHvjmE',
    appId: '1:93249083635:web:25379303a6874c785c7f86',
    messagingSenderId: '93249083635',
    projectId: 'track-efe9f',
    authDomain: 'track-efe9f.firebaseapp.com',
    storageBucket: 'track-efe9f.appspot.com',
    measurementId: 'G-J1YRNWZ2QX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2_sRN7YUhJn71ykmk77k2gu9gN72sHHc',
    appId: '1:93249083635:android:d167dbb642a84b105c7f86',
    messagingSenderId: '93249083635',
    projectId: 'track-efe9f',
    storageBucket: 'track-efe9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHylgMrlfxI0LNvUIKb-t8QnLifNq_8u4',
    appId: '1:93249083635:ios:a55dc121da9f9fb05c7f86',
    messagingSenderId: '93249083635',
    projectId: 'track-efe9f',
    storageBucket: 'track-efe9f.appspot.com',
    iosClientId: '93249083635-dvoaagt3aib6g3tul0t6vbrmp5f23rdk.apps.googleusercontent.com',
    iosBundleId: 'com.example.track',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHylgMrlfxI0LNvUIKb-t8QnLifNq_8u4',
    appId: '1:93249083635:ios:a55dc121da9f9fb05c7f86',
    messagingSenderId: '93249083635',
    projectId: 'track-efe9f',
    storageBucket: 'track-efe9f.appspot.com',
    iosClientId: '93249083635-dvoaagt3aib6g3tul0t6vbrmp5f23rdk.apps.googleusercontent.com',
    iosBundleId: 'com.example.track',
  );
}
